// Generated by https://quicktype.io

export interface Medallas {
    nombre: string;
    medallas: any[];
}

export interface MedallasObject {
    id: number;
    nombre: string;
    medallas: any[];
}
